### ISSUE TITLE
Getting an error if I try to run in EXPO android emulator

### ISSUE THREAD

**Issue by rahu431** [flatlogic/react-native-starter#1]
**Uncaught Error: Can't use AsyncStorage in unsigned Experience.**

I didn't touched any code just downloaded the package and install npm install, when I try to open in Expo XDE. It it gives me this above error. Pls check and let me know.

**Comment by gaykov** [comment]
Hm, that's interesting. But probably not related to React Native Starter.

I've found the file that throws this error from Expo sources: https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/internal/ExponentUnsignedAsyncStorageModule.java

Could you please try to run some other application from your expo XDE? Or maybe try to run it on iOS device or on physical Android device.

**Comment by rahu431** [comment]
Try to use another way to open project on Expo other clients still am getting issue to open, is there any traditional way to open this project by command: "react-native run-android", but this command required ios and android folders inside project folder. Please help me to kick start.

**Comment by gaykov** [comment]
You can open it with expo cli by running `exp start` and then opening your app with a client.

As you said, this problem exist with other apps, so not related to RNS. Going to close this issue. Feel free to ask any other questions here.
