### ISSUE TITLE
Header title issue

### ISSUE THREAD

**Issue by aplt** [flatlogic/react-native-starter#10]
Hey ! First I am new to React Native so maybe what I wrote is not the best way :) 

There is an issue with header title.
"React native starter" is shown on every screen (see attached screenshot).

![screenshot](https://user-images.githubusercontent.com/9114657/51868606-b275da00-234e-11e9-8d91-541a8f703014.png)

This is a partial fix .. 
You must add the following line in ./src/navigation/RootNavigation under defaultNavigationOptions

```
let headerTitle;
if (navigation.state.index > 0) {
     const {routeName} = navigation.state.routes[navigation.state.index];
     headerTitle = routeName;
}      
```
Then return headerTitle

```        
headerTitle: headerTitle,
```

Maybe there is a better way for doing that. Tell us ! :p

**Comment by gaykov** [comment]
Hello @aplt,

Thanks for finding and reporting this issue! Let me have a look and I'll get back here with a fix :)

**Comment by gaykov** [comment]
This one should be fixed in the newest v2 version that's just released.
