### ISSUE TITLE
Convert to Hooks

### ISSUE THREAD

**Issue by dancomanlive** [flatlogic/react-native-starter#14]
Hooks are available from 0.59 so it would be best to start converting the project already :) I am willing to contribute.

**Comment by isaaclem** [comment]
Good idea. I've created a pull request [96bd41152ac](https://github.com/flatlogic/react-native-starter/pull/15/commits/96bd41152ac7d9e80b1547e0f0d0c4090fd0fdd1) to upgrade it to 0.59.1 in order to support hooks. Hopefully the PR can be approved

**Comment by dancomanlive** [comment]
@isaaclem where can I contact you?
