### ISSUE TITLE
Error yarn run:android

### ISSUE THREAD

**Issue by nicolasriccardi** [flatlogic/react-native-starter#18]
yarn run:android
yarn run v1.13.0
$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gaykov** [comment]
Hello @nicolasriccardi!

This issue is not related to the starter kit. Please see this topic: https://stackoverflow.com/questions/32634352/react-native-android-build-failed-sdk-location-not-found
