### ISSUE TITLE
Instructions for running app need updating for expo-cli instead of XDE

### ISSUE THREAD

**Issue by vandor** [flatlogic/react-native-starter#2]
I tried following the instructions in the readme for running the app as-is, and it isn't obvious how to run the project in a simulator without XDE installed (since it's now deprecated in favor of expo-cli). Would you please add instructions for running with the cli instead of expo?

What worked for me:
after 'yarn install', I ran 'expo start'

**Comment by gaykov** [comment]
@vandor thanks for the comment! Will do it in this week's release.

**Comment by gaykov** [comment]
Done in 4d1990b5b7d481de407dee23595ad8344486c41a

Thanks again for reporting this!
