### ISSUE TITLE
Useless and Dangerous 

### ISSUE THREAD

**Issue by rmasonh18** [flatlogic/react-native-starter#24]
Explain what was installed to make my computer fan speed up and run hot? 
Also explain why your starter kit is just a glorious ad campaign to sell your product without any features enabled as touted in the read me such as login etc..

**Comment by gaykov** [comment]
Hi there,

> what was installed to make my computer fan speed up and run hot?

it's node modules probably  ¯\_(ツ)_/¯

Regarding other questions, we'd be happy to help with anything. Let's keep Github issues for code-related conversations. You can contact us at support@reactnativestarter.com with your product-related questions.

Thanks!
