### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by kilimchoi** [flatlogic/react-native-starter#27]
I'm just getting started with react native and I've been running `yarn run:ios` to start the app on the simulator. However, I am unable to debug using `console.log`. Is there a way to see the log statements?

**Comment by gaykov** [comment]
Hi @kilimchoi,

Please check this out: https://facebook.github.io/react-native/docs/debugging

Basically, after setting `console.log` you need to open the developer menu (by hitting `CMD + D` and clicking `Start Remote JS Debugging`) and you'll see your console.log statements in the Chrome console or whatever debugger you prefer to use.

Please, feel free to ask if you have any other questions :)
