### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by davidsonsimoes** [flatlogic/react-native-starter#29]
I am having trouble running the code with the version of node 12.1.0 and I have identified that there are many dependencies in package.json that are in older versions.

<img width="366" alt="Captura de Tela 2019-06-13 às 10 19 26" src="https://user-images.githubusercontent.com/5695277/59436351-d568ce00-8dc5-11e9-9a20-2c3c216b6187.png">

**Comment by gaykov** [comment]
Thanks for submitting the issue! Libs are updated in #47 .
