### ISSUE TITLE
zsh: blue not found

### ISSUE THREAD

**Issue by shafiqueqadri** [flatlogic/react-native-starter#31]
![image](https://user-images.githubusercontent.com/18212311/61075780-2e169f80-a434-11e9-8d28-6f615ab022eb.png)

Theme not found, when i run command ```$THEME_NAME=blue bash change-theme.sh ```

**Comment by shafiqueqadri** [comment]
Hello there,
I have bought the Application.
Kindly help me out with this issue.
Thank you.

**Comment by gaykov** [comment]
He @shafiqueqadri!

Did you resolve this issue? Did you try running the command with `THEME_NAME=blue bash change-theme.sh`?

**Comment by shafiqueqadri** [comment]
Thank you so much @gaykov .
It works.
