### ISSUE TITLE
The development  server returned response error code: 500

### ISSUE THREAD

**Issue by jitanshu** [flatlogic/react-native-starter#41]
Unable to resolve module'./index' from 'D:\react-native-starter\node_modules\react-native\scripts/.'

**Comment by ghmeec** [comment]
Same error here

**Comment by gaykov** [comment]
Hi there!

Thanks for submitting this issue, but I suppose it's not related to React Native Starter, but more to React Native itself. Please have a look at this issue: https://github.com/facebook/react-native/issues/23908

Hope it will help.

Please, feel free to reopen in case if the issue persists!
