### ISSUE TITLE
React Native starter app keeps stopping

### ISSUE THREAD

**Issue by amrs-tech** [flatlogic/react-native-starter#42]
I installed the dependencies and updated some old packages with `npm audit fix`, after the installation completed on my android device, the app doesn't start, it keep on saying **Close App**.

**Screenshot**
![Screenshot_20190909-120648](https://user-images.githubusercontent.com/23120166/64508497-3d627e00-d2fb-11e9-9c08-0752d1526f9f.png)

**Comment by gaykov** [comment]
Hi @amrs-tech!

Do you have any stack trace or some other useful information? It's complicated to tell something just from the screenshot you provided.

**Comment by amrs-tech** [comment]
@gaykov Thanks for the reply but I'm sorry, because for now I am not using the library in my app.

**Comment by gaykov** [comment]
Thanks for the response! I'm going to close the issue for now, but please feel free to reopen if required.

**Comment by amrs-tech** [comment]
@gaykov Thank you!
