### ISSUE TITLE
Problem with ios 13

### ISSUE THREAD

**Issue by federicolucca** [flatlogic/react-native-starter#45]
Hi,
I'm trying to deploy on ios 7, 13.1 . But i have a error:

`Unknown argument type '__attribute__' in method -[RCTAppState getCurrentAppState:error:]. Extend RCTConvert to support this type.
-[RCTModuleMethod processMethodSignature]
    RCTModuleMethod.mm:375
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)`

do i must upgrade the version of RN?

Federico

**Comment by gaykov** [comment]
Hey @federicolucca!

Thanks for submitting the issue. It might be related to the RN version, you are right. Should be fixed in #47.
