### ISSUE TITLE
No bundle URL present.

### ISSUE THREAD

**Issue by ludvigaldrin** [flatlogic/react-native-starter#50]
![Screenshot 2019-12-14 at 16 10 10](https://user-images.githubusercontent.com/15027132/70850581-3d3ec500-1e8c-11ea-8cda-bc7d470f00aa.png)

Just tried the installation and followed every step from scratch (https://docs.reactnativestarter.com/). But when running I get the screen above.

Im thinking of purchasing this but want to see that it works first.

Thanks for your support

**Comment by capitalist** [comment]
You need to be running the packager also `yarn start`

**Comment by ludvigaldrin** [comment]
Dosen't say anywhere in the guide about yarn start. But tried it in root folder anyhow.
Got this error then.

```
Looking for JS files in
   /Users/ludvig/Documents/svipler/spacemer/test/react-native-starter 

Loading dependency graph...2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/ludvig/Documents/svipler/spacemer/test/react-native-starter/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:210:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

More ideas?

**Comment by guardofparadise** [comment]
Please provide us with more information, what kind of OS do you use and which software is helping you with emulation of the mobile device, also please check out this page and make sure that your set up is correct https://facebook.github.io/react-native/docs/getting-started

**Comment by MateoWartelle** [comment]
> Dosen't say anywhere in the guide about yarn start. But tried it in root folder anyhow.
> Got this error then.
> 
> ```
> Loading dependency graph...2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
> 2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
> 2019-12-15 12:39 node[11609] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
> events.js:187
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EMFILE: too many open files, watch
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
> Emitted 'error' event on NodeWatcher instance at:
>     at NodeWatcher.checkedEmitError (/react-native-starter/node_modules/sane/src/node_watcher.js:143:12)
>     at FSWatcher.emit (events.js:210:5)
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
>   errno: -24,
>   syscall: 'watch',
>   code: 'EMFILE',
>   filename: null
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> More ideas?

In the readme it is a bit hidden on how to get started
Run this command to **start the development server** and to start your app on iOS simulator

The "Error: EMFILE: too many open files, watch" I was able to resolve with 

`$ brew update`
`$ brew install watchman`

**Comment by guardofparadise** [comment]
Closed for inactivity
