### ISSUE TITLE
Activity class {com.reactnativestarter/com.reactnativestarter.MainActivity} does not exist

### ISSUE THREAD

**Issue by taobestshop** [flatlogic/react-native-starter#53]
Hi There,

I've purchased the full starter and trying to run in my development environment. I am using windows 10.

I got MainActivity not exist error. Could you help to advise how can I fix this? Thanks.

Below are the detailed info.

===================

C:\Users\xxx\react-native-starter\react-native-starter-full-master>npx react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Task :app:installDebug
10:05:06 V/ddms: execute: running am get-config
10:05:06 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
10:05:06 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Nexus_5X_API_29_x86(AVD) - 10' for app:debug
10:05:06 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
10:05:06 D/Device: Uploading file onto device 'emulator-5554'
10:05:06 D/ddms: Reading file permision of C:\Users\xxx\react-native-starter\react-native-starter-full-master\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
10:05:07 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
10:05:10 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
10:05:10 V/ddms: execute: returning
10:05:10 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
10:05:10 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
10:05:10 V/ddms: execute: returning
Installed on 1 device.

BUILD SUCCESSFUL in 8s
111 actionable tasks: 1 executed, 110 up-to-date
info Running C:\Users\xxx\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
8081
info Starting the app on emulator-5554 (C:\Users\xxx\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 shell am start -n com.reactnativestarter/com.reactnativestarter.MainActivity)...
Starting: Intent { cmp=com.reactnativestarter/.MainActivity }
Error type 3
Error: Activity class {com.reactnativestarter/com.reactnativestarter.MainActivity} does not exist.
=================

**Comment by guardofparadise** [comment]
Hey taobestshop, have you checked out the docs?
https://docs.reactnativestarter.com/#up-and-running-windows
