### ISSUE TITLE
Could not run RNS on ios

### ISSUE THREAD

**Issue by cristiano-c** [flatlogic/react-native-starter#54]
I made a fresh git clone and yarn install, then I run `yarn run:android` and it works fine. But when I run `yarn run:ios` I get following error.

I run:
Catalina 10.15.2
XCode Simulator v11.3.1
yarn 1.19.0

```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

**Comment by guardofparadise** [comment]
Hi Cristiano, please try to remove the build folder YOUR_PROJECT/ios/build/. After this you should be able to run your app through react-native run-ios again. Or try to export variable in console
![d26ee736-0869-11e7-83a2-04e2034903a3](https://user-images.githubusercontent.com/27496705/72801794-f7c3a380-3c52-11ea-855f-2d1a7992a3f0.png)

**Comment by codaabraham** [comment]
> Hi Cristiano, please try to remove the build folder YOUR_PROJECT/ios/build/. After this you should be able to run your app through react-native run-ios again. Or try to export variable in console
> ![d26ee736-0869-11e7-83a2-04e2034903a3](https://user-images.githubusercontent.com/27496705/72801794-f7c3a380-3c52-11ea-855f-2d1a7992a3f0.png)

same issue

**Comment by robertalv** [comment]
run
`yarn start`

then
`yarn run:ios`
