### ISSUE TITLE
I received a package and you receive an error

### ISSUE THREAD

**Issue by oktayatakan** [flatlogic/react-native-starter#56]
![Ekran Resmi 2020-03-10 01 38 33](https://user-images.githubusercontent.com/51229666/76263536-31d31e00-6270-11ea-86cc-9fbe87305e31.png)

**Comment by pythdasch** [comment]
Same for me.

**Comment by pythdasch** [comment]
Solution here: This should appear in the documentation
https://github.com/flatlogic/react-native-starter/issues/50
