### ISSUE TITLE
error in system font, when lauched with expo

### ISSUE THREAD

**Issue by sonu628** [flatlogic/react-native-starter#59]
when launching the application through expo-cli using expo-start, I get the following error

```console.error: "fontFamily "Lato-Regular" is not a system font and has not been loaded through Font.loadAsync. ```

**Comment by hugomn** [comment]
Hi @sonu628, sorry for the off-topic, but how are you running the starter with expo? Thanks!

**Comment by sonu628** [comment]
i did `git clone` of the repo, followed by `yarn install` and then for expo `expo start`.

**Comment by abhidevsgit** [comment]
Is there a way to use expo in this project?

**Comment by guardofparadise** [comment]
Hi Guys, our project works with react-native-cli, we switched to it, please consider using react-native-cli
[https://reactnative.dev/docs/environment-setup](url) > React Native CLI Quickstart
