### ISSUE TITLE
Build Failed in run:android

### ISSUE THREAD

**Issue by ravin-jj** [flatlogic/react-native-starter#60]
Hi,
I'm planning to buy the paid version of your React Native Starter, before that I would like to see the demo and code of the free kit. When I tried to run it I get the following error
![image](https://user-images.githubusercontent.com/52731450/81654761-696a6c00-9453-11ea-907e-41af40a7838e.png)

Please help me with this issue

**Comment by guardofparadise** [comment]
Hi, please check out the docs > [https://docs.reactnativestarter.com/#up-and-running-windows](url)
